name: License Action
author: Ephraim Atta-Duncan
description: GitHub Action for creating license for Projects.

inputs:
  LICENSE_TYPE: # id of input
    description: 'The License Type'
    required: true
    default: 'MIT'
  AUTHOR:
    description: 'Author of Project'
    required: true
  EMAIL:
    description: 'Email of the Author'
    required: true
  PROJECT_NAME:
    description: 'Project Name'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: book-open
  color: blue
