name: License Action
author: Ephraim Atta-Duncan
description: GitHub Action for creating license for Projects.

inputs:
  LICENSE_TYPE: # id of input
    description: 'The License Type'
    required: true
    default: 'MIT'

runs:
  using: 'node12'
  main: 'dist/index.js'
