name: 'units-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./src/index.js
        with:
          LICENSE_TYPE: MIT
          AUTHOR: Ephraim Atta-Duncan
